//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureMessagingServiceBus
{
    using Microsoft.Azure.Amqp.Framing;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AzureEntities1 : DbContext
    {
        public AzureEntities1()
            : base("name=AzureEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AzureMessageLog> AzureMessageLogs { get; set; }
    }

    public class AzureMessageLog
    {
        public string MessageId { get; set; }
        public string SenderId { get; set; }
        public string CreatedTime { get; set; }
        public string Category { get; set; }
        public string Payload { get; set; }

    }
}
